In [1]:
import pandas as pd

In [2]:
t = pd.read_csv('titanic_dataset.csv')
t

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
t.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                   

In [4]:
t.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
t.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
t = t.dropna()

In [7]:
t.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [8]:
t['Sex'] = t.Sex.apply(lambda x: 1 if x == 'female' else 0)

C:\Users\sidal\AppData\Local\Temp\ipykernel_14944\4011354998.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['Sex'] = t.Sex.apply(lambda x: 1 if x == 'female' else 0)


In [9]:
t

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name  Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
6                              McCarthy, Mr. Timothy J    0  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                            Bonnell, Miss. Elizabeth    1  58.0      0   
..                                                 ...  ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)    1  47.0      1   
872                           Carlsson, Mr. Frans Olof    0  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)    1  56.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
889                              Behr, Mr. Karl Howell    0  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [105]:
t.Survived.value_counts()

Survived
1    123
0     60
Name: count, dtype: int64

In [10]:
t['Cabin'].unique()

array(['C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6', 'C23 C25 C27',
       'D33', 'B30', 'C83', 'F33', 'F G73', 'E31', 'A5', 'D10 D12', 'D26',
       'C110', 'B58 B60', 'E101', 'D47', 'B86', 'F2', 'C2', 'B19', 'A7',
       'C49', 'F4', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'B49',
       'D', 'C22 C26', 'C65', 'E36', 'C54', 'B57 B59 B63 B66', 'C7',
       'E34', 'C32', 'B18', 'C124', 'C91', 'E40', 'T', 'E33', 'D37',
       'B35', 'E50', 'C82', 'B96 B98', 'E10', 'C52', 'E44', 'A34', 'C104',
       'C111', 'C92', 'E38', 'E12', 'E63', 'B37', 'C30', 'D20', 'B79',
       'E25', 'D46', 'B73', 'B38', 'B39', 'B22', 'C86', 'C70', 'A16',
       'C101', 'C68', 'A10', 'E68', 'B41', 'A20', 'D19', 'D50', 'D9',
       'A23', 'B50', 'A26', 'D48', 'E58', 'B71', 'B51 B53 B55', 'D49',
       'B5', 'B20', 'F G63', 'C62 C64', 'E24', 'C90', 'C126', 'C45', 'E8',
       'B101', 'C46', 'D30', 'E121', 'D11', 'E77', 'B3', 'D6', 'B

In [11]:
t['Embarked'].unique()

array(['C', 'S', 'Q'], dtype=object)

In [12]:
newe = {'C': 1, 'S': 2, 'Q': 3}
for c in t['Embarked']:
    t['Embarked'] = t['Embarked'].replace(newe)

C:\Users\sidal\AppData\Local\Temp\ipykernel_14944\848472779.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['Embarked'] = t['Embarked'].replace(newe)


In [13]:
t

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name  Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
6                              McCarthy, Mr. Timothy J    0  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                            Bonnell, Miss. Elizabeth    1  58.0      0   
..                                                 ...  ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)    1  47.0      1   
872                           Carlsson, Mr. Frans Olof    0  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)    1  56.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
889                              Behr, Mr. Karl Howell    0  26.0      0   

     Parch    Ticket     Fare        Cabin  Embarked  
1        0  PC 17599  71.2833          C85         1  
3        0    113803  53.1000         C123         2  
6        0     17463  51.8625          E46         2  
10       1   PP 9549  16.7000           G6         2  
11       0    113783  26.5500         C103         2  
..     ...       ...      ...          ...       ...  
871      1     11751  52.5542          D35         2  
872      0       695   5.0000  B51 B53 B55         2  
879      1     11767  83.1583          C50         1  
887      0    112053  30.0000          B42         2  
889      0    111369  30.0000         C148         1  

[183 rows x 12 columns]

In [14]:
t = t.drop(['Cabin', 'Name', 'Ticket'], axis = 1)

In [15]:
t

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
1              2         1       1    1  38.0      1      0  71.2833         1
3              4         1       1    1  35.0      1      0  53.1000         2
6              7         0       1    0  54.0      0      0  51.8625         2
10            11         1       3    1   4.0      1      1  16.7000         2
11            12         1       1    1  58.0      0      0  26.5500         2
..           ...       ...     ...  ...   ...    ...    ...      ...       ...
871          872         1       1    1  47.0      1      1  52.5542         2
872          873         0       1    0  33.0      0      0   5.0000         2
879          880         1       1    1  56.0      0      1  83.1583         1
887          888         1       1    1  19.0      0      0  30.0000         2
889          890         1       1    0  26.0      0      0  30.0000         1

[183 rows x 9 columns]

In [16]:
matrix = t.corr()
matrix

PassengerId  Survived    Pclass       Sex       Age     SibSp  \
PassengerId     1.000000  0.148495 -0.089136  0.025205  0.030933 -0.083488   
Survived        0.148495  1.000000 -0.034542  0.532418 -0.254085  0.106346   
Pclass         -0.089136 -0.034542  1.000000  0.046181 -0.306514 -0.103592   
Sex             0.025205  0.532418  0.046181  1.000000 -0.184969  0.104291   
Age             0.030933 -0.254085 -0.306514 -0.184969  1.000000 -0.156162   
SibSp          -0.083488  0.106346 -0.103592  0.104291 -0.156162  1.000000   
Parch          -0.051454  0.023582  0.047496  0.089581 -0.271271  0.255346   
Fare            0.029740  0.134241 -0.315235  0.130433 -0.092424  0.286433   
Embarked        0.021576 -0.108914  0.214796 -0.059453 -0.077790  0.089959   

                Parch      Fare  Embarked  
PassengerId -0.051454  0.029740  0.021576  
Survived     0.023582  0.134241 -0.108914  
Pclass       0.047496 -0.315235  0.214796  
Sex          0.089581  0.130433 -0.059453  
Age         -0.271271 -0.092424 -0.077790  
SibSp        0.255346  0.286433  0.089959  
Parch        1.000000  0.389740  0.057653  
Fare         0.389740  1.000000 -0.227926  
Embarked     0.057653 -0.227926  1.000000

In [17]:
t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 1 to 889
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  183 non-null    int64  
 1   Survived     183 non-null    int64  
 2   Pclass       183 non-null    int64  
 3   Sex          183 non-null    int64  
 4   Age          183 non-null    float64
 5   SibSp        183 non-null    int64  
 6   Parch        183 non-null    int64  
 7   Fare         183 non-null    float64
 8   Embarked     183 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 14.3 KB


In [18]:
#relação de sobrevivência forte com sexo e idade

In [62]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
x = t.drop('Survived', axis = 1)
y = t['Survived']
xtreino, xteste, ytreino, yteste = train_test_split(x, y, test_size=0.33, random_state=42)
log = LogisticRegression(random_state=0).fit(xtreino, ytreino)
log

C:\Users\sidal\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [63]:
from sklearn import svm
svm = svm.SVC().fit(xtreino, ytreino)
svm

SVC()

In [82]:
print(x.shape)
print(y.shape)
y = y.reshape(-1, 1)
print(y.shape)

(183, 8)
(61, 3)
(183, 1)


In [83]:
from sklearn.metrics import accuracy_score
xtreinopredlog = log.predict(xtreino)
xtreinopredlog

array([1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [92]:
print(xtreino.shape)
print(xteste.shape)
print(ytreino.shape)
print(yteste.shape)
ytreino = ytreino.reshape(-1, 1)
yteste = yteste.reshape(-1, 1)

(122, 8)
(61, 8)
(122, 1)
(61, 1)


In [97]:
#accuracy score of training data

In [100]:
xtreinopredsvm = svm.predict(xtreino)
xtreinopredsvm

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [101]:
acc1 = accuracy_score(ytreino, xtreinopredlog)
print(acc1)
acc2 = accuracy_score(ytreino, xtreinopredsvm)
print(acc2)

0.7950819672131147
0.6967213114754098


In [98]:
#accuracy score of test data

In [99]:
xtestepredlog = log.predict(xteste)
xtestepredlog

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [102]:
xtestepredsvm = svm.predict(xteste)
xtestepredsvm

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [103]:
acc1 = accuracy_score(yteste, xtestepredlog)
print(acc1)
acc2 = accuracy_score(yteste, xtestepredsvm)
print(acc2)

0.7049180327868853
0.6229508196721312
